/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "var(--color-inverse-surface)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary": "var(--color-on-tertiary)",
        "inverse-primary": "var(--color-inverse-primary)",
        "secondary-container": "var(--color-secondary-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-error": "var(--color-on-error)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "background": "var(--color-background)",
        "secondary": "var(--color-secondary)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-tint": "var(--color-surface-tint)",
        "on-primary": "var(--color-on-primary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-container-low": "var(--color-surface-container-low)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "text-main": "var(--color-text-main)",
        "outline": "var(--color-outline)",
        "tertiary-container": "var(--color-tertiary-container)",
        "primary-container": "var(--color-primary-container)",
        "success-green": "var(--color-success-green)",
        "primary": "var(--color-primary)",
        "surface-bright": "var(--color-surface-bright)",
        "error": "var(--color-error)",
        "on-error-container": "var(--color-on-error-container)",
        "neutral-bg": "var(--color-neutral-bg)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-container": "var(--color-surface-container)",
        "surface": "var(--color-surface)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary": "var(--color-tertiary)",
        "on-background": "var(--color-on-background)",
        "error-container": "var(--color-error-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "surface-variant": "var(--color-surface-variant)",
        "outline-variant": "var(--color-outline-variant)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-surface-variant": "var(--color-on-surface-variant)",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        gutter: "24px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "container-max": "1280px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        heading: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.25", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["52px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-md": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "1.35", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        card: "var(--shadow-sm)",
        elevated: "var(--shadow-md)",
        float: "var(--shadow-lg)",
        hero: "var(--shadow-xl)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out forwards",
        "slide-up": "slideUp 0.5s ease-out forwards",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
