/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303032",
        "on-primary-fixed": "#101b30",
        "surface-container-high": "#eae7e9",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#bbc6e2",
        "secondary-container": "#036cfb",
        "primary-fixed-dim": "#bbc6e2",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#3c475d",
        "on-secondary-fixed-variant": "#00419e",
        "inverse-on-surface": "#f3f0f2",
        "secondary-fixed": "#dae2ff",
        "on-surface": "#1b1b1d",
        "background": "#fbf8fb",
        "secondary": "#0055c9",
        "surface-dim": "#dcd9db",
        "surface-tint": "#545e76",
        "on-primary": "#ffffff",
        "on-secondary-container": "#fefcff",
        "on-tertiary-fixed": "#271901",
        "tertiary-fixed-dim": "#dfc299",
        "surface-container-low": "#f5f3f5",
        "tertiary-fixed": "#fcdeb3",
        "text-main": "#212529",
        "outline": "#75777d",
        "tertiary-container": "#332306",
        "primary-container": "#1b263b",
        "success-green": "#198754",
        "primary": "#051125",
        "surface-bright": "#fbf8fb",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "neutral-bg": "#F8F9FA",
        "on-tertiary-fixed-variant": "#574423",
        "on-primary-container": "#828da7",
        "surface-container": "#f0edef",
        "surface": "#fbf8fb",
        "surface-container-highest": "#e4e2e4",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#a28963",
        "tertiary": "#1a0f00",
        "on-background": "#1b1b1d",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b1c5ff",
        "surface-variant": "#e4e2e4",
        "outline-variant": "#c5c6cd",
        "on-secondary-fixed": "#001946",
        "primary-fixed": "#d7e2ff",
        "on-surface-variant": "#45474d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "container-max": "1280px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}